#pragma once
#include <QString>

#define APP_TITLE          "Лабораторная работа: Последовательности"
#define TAB_OPERATIONS     "Операции"
#define TEXT_SETTINGS      "Настройки"
#define TYPE_INT           "int"
#define TYPE_DOUBLE        "double"
#define CONT_ARRAY         "Array"
#define CONT_LIST          "List"
#define CONT_BIT           "Bit"
#define TEXT_DATA_TYPE     "Тип данных"
#define TEXT_CONTAINER     "Контейнер"
#define TEXT_OPERATION     "Операция"
#define TEXT_SEQ_A         "Последовательность A"
#define TEXT_SEQ_B         "Последовательность B"
#define TEXT_ARGS          "Аргументы"
#define TEXT_VALUE         "Значение"
#define TEXT_INDEX         "Индекс"
#define TEXT_START         "Начало"
#define TEXT_END           "Конец"
#define TEXT_RUN           "Выполнить"
#define TEXT_GROUP_RESULT  "Результат"
#define TEXT_RESULT_LBL    "Результат:"
#define ERR_TITLE          "Ошибка"
#define ERR_INVALID_INPUT  "Некорректный ввод или неверная операция"

#define STYLE_MAIN "QMainWindow { background-color: #f0f0f0; }"
#define STYLE_LABEL_RESULT  "font-weight: bold; font-size: 16px; color: #333;"